//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinalDeCurso.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-78GVLJB\\SQLSERVER;Initial Catalog=Servicios_de_mantenimiento;" +
            "Integrated Security=True")]
        public string Servicios_de_mantenimientoConnectionString {
            get {
                return ((string)(this["Servicios_de_mantenimientoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-78GVLJB\\SQLSERVER;Initial Catalog=Servicio_de_Mantenimiento;P" +
            "ersist Security Info=True;User ID=Jeison;Password=Jeison.2020")]
        public string Servicio_de_MantenimientoConnectionString {
            get {
                return ((string)(this["Servicio_de_MantenimientoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=Servicio_de_Mantenimiento;Integrated Security=True")]
        public string Servicio_de_MantenimientoConnectionString1 {
            get {
                return ((string)(this["Servicio_de_MantenimientoConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-6891DS78;Initial Catalog=Servicios_de_mantenimiento;Persist Se" +
            "curity Info=True;User ID=AdminMantenimiento;Password=proyecto123")]
        public string Servicios_de_mantenimientoConnectionString1 {
            get {
                return ((string)(this["Servicios_de_mantenimientoConnectionString1"]));
            }
        }
    }
}
